const PRODUTOS = [
  {
    cod: "105",
    nome: "GALINHA CONGELADA C/ MIÚDOS",
    empresa: "Acreaves",
    marca: "ACREAVES",
    grupo: "INTEIRO",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/mZSDzkRK/105-Galinha-congelada-Acreaves-Copia-removebg-preview.png"],
    desc: "Sabor autêntico e marcante para receitas tradicionais. Ideal para caldos ricos e cozidos de cozimento lento que exigem mais consistência e aroma."
  },
  {
    cod: "102",
    nome: "FRANGO RESFRIADO C/MIUDOS",
    empresa: "Acreaves",
    marca: "ACREAVES",
    grupo: "INTEIRO",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "20 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A 7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/FFxRdzNt/102-Frango-Resfriado-Acreaves-Copia-removebg-preview.png"],
    desc: "Frango inteiro selecionado, mantido em baixas temperaturas sem congelamento. Por ser resfriado, mantém a textura da carne mais macia e está pronto para o preparo imediato, facilitando o tempero e o cozimento."
  },
  {
    cod: "104",
    nome: "FRANGO CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "INTEIRO",
    tipo: "CONGELADO",
    complemento: "CX / CONTENDO 8 A 9 UNIDADES (PESO VARIÁVEL)",
    peso: "Aprox. 20 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/vTBqNmwf/001-V01-SABBOR-Frango-Congelado-mockup.jpg"],
    desc: "Praticidade que acompanha o seu ritmo sem abrir mão do Sabbor. Da grelha ao forno, nosso frango congelado é a base perfeita para buscar saúde e versatilidade na cozinha."
  },
  {
    cod: "112",
    nome: "FRANGO CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "INTEIRO",
    tipo: "CONGELADO",
    complemento: "CX / CONTENDO 9 A 10 UNIDADES (PESO VARIÁVEL)",
    peso: "Aprox. 20 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/vTBqNmwf/001-V01-SABBOR-Frango-Congelado-mockup.jpg"],
    desc: "Praticidade que acompanha o seu ritmo sem abrir mão do Sabbor. Da grelha ao forno, nosso frango congelado é a base perfeita para buscar saúde e versatilidade na cozinha."
  },
  {
    cod: "115",
    nome: "AVE NATALINA SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "INTEIRO",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "20 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/gjJST0bD/021-V02-SABBOR-AVE-NATALINA-mockup.jpg"],
    desc: "A estrela das celebrações. Ave selecionada com tempero especial Sabbor, garantindo carne suculenta, pele dourada, sabor inconfundível e termômetro para assar."
  },
  {
    cod: "249",
    nome: "COXINHA DA ASA CONGELADA NA BANDEJA",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "BANDEJA",
    tipo: "CONGELADO",
    complemento: "1 kg — 14 un",
    peso: "14 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/kG41p5PH/234-V00-SABBOR-Coxinha-da-Asa-Congelada-mockup.jpg"],
    desc: "O corte favorito do churrasco e do happy hour. Carnuda e saborosa, com padronização de tamanho na bandeja."
  },
  {
    cod: "248",
    nome: "FILÉ DA COXA CONGELADO NA BANDEJA",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "BANDEJA",
    tipo: "CONGELADO",
    complemento: "1 kg — 14 un",
    peso: "14 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/nrzRPLfw/233-V00-SABBOR-File-de-Coxa-e-Sobrecoxa-Congelado-mockup.jpg"],
    desc: "Sabor da coxa com a praticidade do filé. Sem ossos e peles, ideal para grelhados rápidos e estrogonofe suculento."
  },
  {
    cod: "247",
    nome: "COXA E SOBRECOXA CONGELADA NA BANDEJA",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "BANDEJA",
    tipo: "CONGELADO",
    complemento: "1 kg — 14 un",
    peso: "14 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/4ydLS3R8/232-V00-SABBOR-Coxa-e-Sobrecoxa-Congelada-mockup.jpg"],
    desc: "O combo perfeito de rendimento e sabor. Peças selecionadas que garantem uma refeição completa para toda a família."
  },
  {
    cod: "246",
    nome: "MEIO DA ASA CONGELADA NA BANDEJA",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "BANDEJA",
    tipo: "CONGELADO",
    complemento: "1 kg — 14 un",
    peso: "14 kg",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/QCt4yMZS/231-V00-SABBOR-Meio-da-Asa-Congelada-mockup.jpg"],
    desc: "Qualidade premium para quem busca o melhor da asa (Tulipa). Ideal para receitas especiais e preparos crocantes."
  },
  {
    cod: "245",
    nome: "FILÉ DE PEITO CONGELADO NA BANDEJA",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "BANDEJA",
    tipo: "CONGELADO",
    complemento: "1 kg — 14 un",
    peso: "14 kg",
    conserva: "CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/90M8nfHY/230-V00-SABBOR-File-de-Peito-Congelado-mockup.jpg"],
    desc: "Praticidade máxima: filés limpos e padronizados. Ideal para o consumidor que busca rapidez e zero desperdício."
  },
  {
    cod: "225",
    nome: "COXA E SOBRECOXA CONGELADA SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/RFBsC77p/SABBOR-Cortes-Coxa-e-sobrecoxa-225.png"],
    desc: "Cortes de coxa e sobrecoxa de frango, congelados, ideais para diversas preparações, com suculência e sabor garantidos."
  },
  {
    cod: "226",
    nome: "FILÉ DE PEITO CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/cHBDvvTL/SABBOR-Cortes-File-de-peito-226.png"],
    desc: "Filé de peito de frango sem osso, congelado, prático e versátil, ideal para grelhados e receitas saudáveis."
  },
  {
    cod: "227",
    nome: "PEITO DE FRANGO CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/90XLZcNM/SABBOR-Cortes-Peito-227.png"],
    desc: "Peito de frango congelado, corte nobre com baixo teor de gordura, ideal para diversas preparações."
  },
  {
    cod: "239",
    nome: "COXINHA DA ASA CONGELADA SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/pTHGVff6/SABBOR-Cortes-Coxinha-da-asa-239.png"],
    desc: "Coxinha da asa de frango, congelada, perfeita para frituras e petiscos crocantes."
  },
  {
    cod: "240",
    nome: "MEIO + PONTA DA ASA CONGELADA SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/Y02dYty0/SABBOR-Cortes-Meio-ponta-da-asa-240.png"],
    desc: "Cortes de asa (meio e ponta), congelados, ideais para assados e frituras com ótimo rendimento."
  },
  {
    cod: "241",
    nome: "DORSO CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "15 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/nzGdXXTH/SABBOR-Cortes-Dorso-241.png"],
    desc: "Dorso de frango congelado, indicado para caldos e preparo de receitas caseiras."
  },
  {
    cod: "242",
    nome: "ASA CONGELADA SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/Qt34NQQn/SABBOR-Cortes-Asa-242.png"],
    desc: "Asa de frango inteira, congelada, ideal para churrasco, fritura ou preparo no forno."
  },
  {
    cod: "243",
    nome: "SOBRE COXA SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/tJRBW9mn/SABBOR-Cortes-Sobrecoxa-243.png"],
    desc: "Sobrecoxa de frango, corte suculento e macio, ideal para diversas preparações do dia a dia."
  },
  {
    cod: "244",
    nome: "MEIO DA ASA CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "15 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/L54xLm0m/SABBOR-Cortes-Meio-da-asa-244.png"],
    desc: "Meio da asa de frango, congelado, perfeito para fritar ou assar, com textura macia e sabor marcante."
  },
  {
    cod: "320",
    nome: "CORAÇÃO CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/90XLZcNG/SABBOR-Miudos-Coracao-320.png"],
    desc: "Coração de frango congelado, ideal para churrasco e petiscos, com sabor característico e maciez."
  },
  {
    cod: "323",
    nome: "KIT DE CANJA CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/vT80fGSv/SABBOR-Miudos-Kit-Canja-323.png"],
    desc: "Kit com cortes selecionados de frango para preparo de canja, garantindo praticidade e sabor caseiro."
  },
  {
    cod: "321",
    nome: "MOELA CONGELADA SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/BbZmHJwM/SABBOR-Miudos-Moela-321.png"],
    desc: "Moela de frango congelada, ideal para cozidos e receitas tradicionais, com textura firme e sabor intenso."
  },
  {
    cod: "322",
    nome: "PÉ DE FRANGO CONGELADO SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/x8GtNqFx/PE-DE-FRANGO-322.png"],
    desc: "Pé de frango congelado, indicado para caldos ricos e gelatinosos, muito utilizado na culinária tradicional."
  },
  {
    cod: "324",
    nome: "COXA/SOBRECOXA PORÇÃO DORSAL CONG SABBOR",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/MTSPZ77N/SABBOR-Cortes-Coxa-e-sobrecoxa-dorsal-324.png"],
    desc: "Cortes de coxa e sobrecoxa com porção dorsal, congelados, oferecendo ótimo custo-benefício e sabor."
  },
  {
    cod: "410",
    nome: "FRANGO A PASSARINHO CONGELADO MARINADO",
    empresa: "Acreaves",
    marca: "SABBOR",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "20 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/L8xpp04h/Whats-App-Image-2026-04-29-at-6-49-06-PM.png"],
    desc: "O petisco perfeito para qualquer momento. Cortes selecionados de frango, marinados em um tempero especial que garante suculência por dentro e crocância por fora. Pronto para o preparo, oferece agilidade na cozinha e o sabor irresistível que agrada a todos."
  },
  {
    cod: "50632",
    nome: "SALSICHA HOT DOG CONGELADA",
    empresa: "Acreaves",
    marca: "FRIATO",
    grupo: "EMBUTIDOS",
    tipo: "CONGELADO",
    complemento: "5 kg — 4 un",
    peso: "20 kg",
    conserva: "MANTENHA CONGELADO -12 C OU MAIS FRIO",
    promo: false,
    imgs: ["https://i.postimg.cc/Vk6tQd1q/50632.png"],
    desc: "Sabor e textura ideais para o hot dog perfeito. Versátil e prática, nossa salsicha mantém a suculência e o padrão de qualidade da grelha ao cozimento."
  },
  {
    cod: "20561",
    nome: "FILÉ DA PANCETA SUÍNA TEMPERADA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/NF2NGdyB/20561-V01-Mister-Pig-File-de-Panceta-Suina-Temperada-Congelada-mockup.png"],
    desc: "Corte nobre da panceta suína, já temperado, ideal para assados crocantes e suculentos."
  },
  {
    cod: "20562",
    nome: "PERNIL SUÍNO TEMPERADO",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 20 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/Vv07sKSY/20562-V01-Mister-Pig-Pernil-Suino-Temperado-Congelado.png"],
    desc: "Pernil suíno selecionado e temperado, pronto para assar, garantindo maciez e sabor caseiro."
  },
  {
    cod: "20914",
    nome: "PICANHA SUÍNA TEMPERADA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADA A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/SQXqzqCn/20914-V01-Mister-Pig-Picanha-Suina-Temperada-Congelada.png"],
    desc: "Corte nobre suíno, já temperado, ideal para churrascos com maciez e suculência."
  },
  {
    cod: "20915",
    nome: "COSTELA SUÍNA TEMPERADA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADA A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/SQXqzqCM/20915-V01-Mister-Pig-Costela-Suina-Temperada-Congelada-mockup.png"],
    desc: "Costela suína temperada, perfeita para assados lentos, garantindo sabor intenso."
  },
  {
    cod: "20916",
    nome: "LOMBO SUÍNO TEMPERADO",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGEADA A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/2jqmBmhd/20916-V01-Mister-Pig-Lombo-Suino-Temperado-Congelado.png"],
    desc: "Lombo suíno selecionado, já temperado, ideal para assar ou grelhar."
  },
  {
    cod: "20986",
    nome: "FRALDINHA SUÍNA TEMPERADA CONGELADA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/8kqGR3bT/20986-V01-Mister-Pig-Fraldinha-Suina-Temperada-Congelada-mockup.png"],
    desc: "Corte suíno selecionado, já temperado, ideal para preparo rápido com sabor marcante e suculência garantida."
  },
  {
    cod: "20856",
    nome: "FRALDINHA SUÍNA TEMPERADA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "TEMPERADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/VvXjrvQr/20856.jpg"],
    desc: "Corte nobre e extremamente macio. O tempero suave realça o sabor natural da carne suína. Sucesso garantido na brasa."
  },
  {
    cod: "20227",
    nome: "Bisteca de Carré Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 20 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/pVfhWcJz/20227.png"],
    desc: "Corte suíno congelado, com osso, ideal para grelha ou fritura, garantindo sabor e suculência."
  },
  {
    cod: "20231",
    nome: "Lombo Suíno Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/MZ7M63mf/20231.png"],
    desc: "Corte magro e macio, congelado, ideal para assados e preparações variadas."
  },
  {
    cod: "20500",
    nome: "Carré com Costela e Barriga",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 25 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/Y26GrDzW/20500.png", "https://i.postimg.cc/LsgFjNTx/20500-1.png", "https://i.postimg.cc/Zqvz6Vcf/20500-2.png", "https://i.postimg.cc/QMKZc0b0/20500-3.png", "https://i.postimg.cc/Zqvz6Vcj/20500-4.png"],
    desc: "Corte suíno completo com costela e barriga, ideal para churrasco e assados."
  },
  {
    cod: "20569",
    nome: "Pernil Suíno com Osso e Pele Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/G3F8LgxY/20569.png"],
    desc: "Corte tradicional com osso e pele, perfeito para assados suculentos."
  },
  {
    cod: "20577",
    nome: "Bisteca de Carré com Pele",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/KcPkGpDr/20577.png"],
    desc: "Bisteca suína com pele, proporcionando mais sabor e crocância ao preparo."
  },
  {
    cod: "20710",
    nome: "Filé Mignon Suíno Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/kMQ6JYvN/20710.png", "https://i.postimg.cc/tT0QkWSd/20710-1.png", "https://i.postimg.cc/LXdKDLCB/20710-2.png", "https://i.postimg.cc/d1MP6rH9/20710-3.png", "https://i.postimg.cc/nz8b2BRk/20710-4.png"],
    desc: "Corte nobre, macio e suculento, ideal para receitas sofisticadas."
  },
  {
    cod: "20712",
    nome: "Carré Suíno Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/05YMkX00/20712.png"],
    desc: "Corte com osso, ideal para grelha ou forno, com excelente sabor."
  },
  {
    cod: "20714",
    nome: "Picanha Suína Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/bYxDyV9T/20714.png", "https://i.postimg.cc/G20wKG7M/20714-1.png", "https://i.postimg.cc/KzXSfBq0/20714-2.png", "https://i.postimg.cc/tT0QkWSS/20714-3.png", "https://i.postimg.cc/k4r3sK1Y/20714-4.png"],
    desc: "Corte especial, macio e suculento, ideal para churrasco."
  },
  {
    cod: "20717",
    nome: "Pernil Suíno Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/c4dKr7FB/20717.png"],
    desc: "Corte tradicional, versátil e ideal para assados."
  },
  {
    cod: "20718",
    nome: "Paleta Suína Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 15 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/c4dKr7FM/20718.png", "https://i.postimg.cc/QtLGm1Yr/20718-1.png", "https://i.postimg.cc/Tw8M0gNG/20718-2.png", "https://i.postimg.cc/C1yT7krF/20718-3.png", "https://i.postimg.cc/KzXSfBpc/20718-4.png"],
    desc: "Corte com excelente custo-benefício, ideal para cozidos e assados."
  },
  {
    cod: "20720",
    nome: "Bisteca de Copa Lombo Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/9Fc4rPLp/20720.png"],
    desc: "Corte marmorizado, suculento e ideal para grelha."
  },
  {
    cod: "20721",
    nome: "Pele Suína Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 20 kg",
    conserva: "MANTENHA CONGELADA A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/CLwZzCc7/20721.png", "https://i.postimg.cc/mDxfjCpB/20721-1.png", "https://i.postimg.cc/RFcrDh2m/20721-2.png", "https://i.postimg.cc/LXzdb5G9/20721-3.png", "https://i.postimg.cc/V6jyVv2z/20721-4.png"],
    desc: "Produto ideal para preparo de torresmo e derivados."
  },
  {
    cod: "20724",
    nome: "Costela Suína em Manta Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/fTM3J78r/20724.png", "https://i.postimg.cc/4dzCSyj4/20724-1.png", "https://i.postimg.cc/9MG3n0sf/20724-2.png", "https://i.postimg.cc/ZRrkMnXn/20724-3.png", "https://i.postimg.cc/3RgMcNzW/20724-4.png"],
    desc: "Costela inteira em manta, ideal para assados e churrasco."
  },
  {
    cod: "20725",
    nome: "Costela Suína Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/hPKJf82y/20725.png"],
    desc: "Corte saboroso, ideal para churrasco e forno."
  },
  {
    cod: "20732",
    nome: "Alcatra Suína Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/m2Tct3mp/20732.png", "https://i.postimg.cc/4ysCkZTK/20732-1.png", "https://i.postimg.cc/Gtd0wr1y/20732-2.png", "https://i.postimg.cc/FzNt5mQ3/20732-3.png", "https://i.postimg.cc/brpXc8jQ/20732-4.png"],
    desc: "Corte nobre, macio e versátil."
  },
  {
    cod: "20738",
    nome: "Copa Lombo Suíno Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/15ygf0vY/20735.png"],
    desc: "Corte suculento e macio, ideal para grelha."
  },
  {
    cod: "20739",
    nome: "Ponta de Costela Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/hPKJf82N/20738.png"],
    desc: "Parte saborosa da costela, ideal para cozidos e assados."
  },
  {
    cod: "20744",
    nome: "Pés Suínos Congelados",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/fTM3J786/20739.png", "https://i.postimg.cc/VvmyQ1cZ/20744-1.png", "https://i.postimg.cc/yxsq4Bzb/20744-2.png", "https://i.postimg.cc/QChLGsrz/20744-3.png", "https://i.postimg.cc/SRk0FqpH/20744-4.png"],
    desc: "Produto tradicional para feijoadas e caldos."
  },
  {
    cod: "20746",
    nome: "Máscara com Orelha Suína Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/7YqCf1B8/20744.png"],
    desc: "Corte típico para pratos regionais."
  },
  {
    cod: "20735",
    nome: "Joelho Suíno Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/X7nZpK26/20746.png", "https://i.postimg.cc/prRNbxtf/20735-1.png", "https://i.postimg.cc/sxsFdyRP/20735-2.png", "https://i.postimg.cc/Xq4MS30k/20735-3.png", "https://i.postimg.cc/8cN8QDVb/20735-4.png"],
    desc: "Corte ideal para preparo de pratos típicos e assados."
  },
  {
    cod: "20763",
    nome: "Meia Carcaça Suína Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 40 kg",
    conserva: "MANTENHA CONGELADA A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/qMptzcmd/20763.png"],
    desc: "Produto inteiro para cortes personalizados."
  },
  {
    cod: "20766",
    nome: "Pernil Suíno Bolinha Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/8Pw7WFYn/20766.png", "https://i.postimg.cc/PfQsbLmW/20766-1.png", "https://i.postimg.cc/Y2zKN41N/20766-2.png", "https://i.postimg.cc/c1By7KQw/20766-3.png", "https://i.postimg.cc/wxQ85thF/20766-4.png"],
    desc: "Corte arredondado, ideal para porcionamento."
  },
  {
    cod: "20769",
    nome: "Costela Premium Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/c4TvYKzp/20769.png", "https://i.postimg.cc/gcHFywvD/20769-1.png", "https://i.postimg.cc/h41W8J9s/20769-2.png", "https://i.postimg.cc/KcDS7Kn6/20769-3.png", "https://i.postimg.cc/xj3DGkKW/20769-4.png"],
    desc: "Corte selecionado com alto padrão de qualidade."
  },
  {
    cod: "20770",
    nome: "Carré Sem Couro Inteiro Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 20 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/8Pw7WF3Q/20770.png"],
    desc: "Corte inteiro sem pele, ideal para assados."
  },
  {
    cod: "20772",
    nome: "Carré Inteiro com Couro Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 20 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/Ghz4YBNr/20772.png"],
    desc: "Corte completo com pele, ideal para preparos crocantes."
  },
  {
    cod: "20923",
    nome: "Bisteca de Pernil Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/kXw28VZ2/20923.png"],
    desc: "Corte com osso, ideal para fritura e grelha."
  },
  {
    cod: "20925",
    nome: "Barriga Suína Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/KvQ1LKVc/20925.png", "https://i.postimg.cc/4N4CWJPk/20925-1.png", "https://i.postimg.cc/rFy6f8jk/20925-2.png", "https://i.postimg.cc/X7NMsVL3/20925-3.png", "https://i.postimg.cc/ncV83H2p/20925-4.png"],
    desc: "Corte suculento com excelente camada de gordura, ideal para preparo de torresmo, assados e receitas que valorizam sabor e maciez."
  },
  {
    cod: "20928",
    nome: "Sobrepaleta Suína em Cubos Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 20 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/gk4xRw5w/20928.png"],
    desc: "Corte sem osso em cubos, pronto para preparo."
  },
  {
    cod: "20985",
    nome: "Pernil Desossado com Pele Congelado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/qMQNntYh/20985.png"],
    desc: "Corte prático e suculento para assados."
  },
  {
    cod: "20989",
    nome: "Paleta Suína Bolinha Congelada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES CONGELADOS",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/NjM5xsqf/20989.png", "https://i.postimg.cc/CLMycF7z/20989-1.png", "https://i.postimg.cc/J47wp1xs/20989-2.png", "https://i.postimg.cc/Yq2cdpR4/20989-3.png", "https://i.postimg.cc/4N4CWJP7/20989-4.png"],
    desc: "Corte suíno congelado, com formato arredondado e excelente rendimento, ideal para assados, cozidos e preparações diversas, garantindo sabor e suculência."
  },
  {
    cod: "20579",
    nome: "Costela Suína Premium sem Pele Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/sDn2xkQY/20579.png"],
    desc: "Corte selecionado, pronto para preparo."
  },
  {
    cod: "20711",
    nome: "Filé Mignon Suíno Resfriado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/65HQqk2n/20711.png"],
    desc: "Corte nobre e macio, pronto para consumo."
  },
  {
    cod: "20715",
    nome: "Picanha Suína Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/x1c1z6MN/20715.png"],
    desc: "Corte suculento ideal para churrasco."
  },
  {
    cod: "20716",
    nome: "Pernil Suíno Resfriado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 16 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/nhChD3Bs/20716.png"],
    desc: "Corte tradicional pronto para preparo."
  },
  {
    cod: "20719",
    nome: "Paleta Suína Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "15 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/kgBgbTKN/20719.png"],
    desc: "Corte versátil com excelente sabor."
  },
  {
    cod: "20726",
    nome: "Costela Suína Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/W1h1k5g6/20726.png"],
    desc: "Corte ideal para churrasco."
  },
  {
    cod: "20733",
    nome: "Alcatra Suína Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/L8n81xLN/20733.png"],
    desc: "Corte nobre e macio."
  },
  {
    cod: "20737",
    nome: "Copa Lombo Suíno Resfriado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/0ybywVDf/20737.png"],
    desc: "Corte suculento pronto para preparo."
  },
  {
    cod: "20745",
    nome: "Costela Suína Premium Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/fRpTjYfC/20745.png"],
    desc: "Corte selecionado de alta qualidade."
  },
  {
    cod: "20751",
    nome: "Lombo Suíno Resfriado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/RZyVQwLp/20751.png"],
    desc: "Corte magro e versátil."
  },
  {
    cod: "20748",
    nome: "Carcaça Suína Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 40 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/DwHyd1PD/20748.png"],
    desc: "Produto inteiro para cortes diversos."
  },
  {
    cod: "20924",
    nome: "Barriga Suína Resfriada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTES RESFRIADOS",
    tipo: "RESFRIADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/2SM8Fn7X/20924.png"],
    desc: "Corte suculento, ideal para torresmo e assados."
  },
  {
    cod: "20608",
    nome: "MORTADELA TRADICIONAL",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "EMBUTIDOS",
    tipo: "DEFUMADOS",
    complemento: "2,5 kg — 6 un",
    peso: "15 kg",
    conserva: "MATENHA EM LOCAL SECO E FRESCO ATÉ +25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/mk1dZmcr/20608-SABBOR-Mortadela-2-5-kg-mockup.png"],
    desc: "Mortadela tradicional, macia e saborosa, ideal para lanches e consumo diário."
  },
  {
    cod: "20609",
    nome: "MORTADELA TRADICIONAL 400 G",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "EMBUTIDOS",
    tipo: "DEFUMADOS",
    complemento: "400 g — 25 un",
    peso: "10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ +25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/1XVWRvgf/20609-SABBOR-Mortadela-400-g-mockup.png"],
    desc: "Mortadela tradicional em embalagem prática, perfeita para lanches rápidos e porções menores."
  },
  {
    cod: "20629",
    nome: "SALSICHA DE FRANGO RESFRIADA",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "EMBUTIDOS",
    tipo: "RESFRIADO",
    complemento: "3 kg — 5 un",
    peso: "15 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A 7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/5jcsX8vC/20629-SABBOR-Salsicha-de-Frango-Resfriada-3-kg-mockup.png"],
    desc: "Salsicha de frango leve e saborosa, ideal para preparo rápido. Produto resfriado."
  },
  {
    cod: "20630",
    nome: "SALSICHA HOT DOG RESFRIADA",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "EMBUTIDOS",
    tipo: "RESFRIADO",
    complemento: "3 kg — 5 un",
    peso: "15 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A 7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/vDR04595/20630-V01-SABBOR-Salsicha-Resfriada-3-kg-mockup.png"],
    desc: "Salsicha tipo hot dog, macia e suculenta, perfeita para lanches rápidos. Produto resfriado."
  },
  {
    cod: "20631",
    nome: "SALSICHA HOT DOG CONGELADA",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "EMBUTIDOS",
    tipo: "CONGELADO",
    complemento: "4 kg — 4 un",
    peso: "16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/XXMsr9Fd/20631-SABBOR-Salsicha-Hot-Dog-Congelada-4-kg-mockup.png"],
    desc: "Salsicha hot dog congelada, prática e com maior durabilidade, mantendo sabor e qualidade."
  },
  {
    cod: "20638",
    nome: "MORTADELA TIPO BOLOGNA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "EMBUTIDOS",
    tipo: "DEFUMADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO ATÉ +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/c6qFvfYD/20638-V01-Mister-Pig-Mortadela-Tipo-Bologna-GRANDE.png"],
    desc: "Mortadela tipo Bologna, com textura diferenciada e sabor suave, ideal para sanduíches."
  },
  {
    cod: "20615",
    nome: "PRESUNTO COZIDO SABBOR 3.6KG",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "EMBUTIDOS",
    tipo: "RESFRIADO",
    complemento: "3,6 kg — 3 un",
    peso: "10,8 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/FzkPFTfk/20615-SABBOR-Presunto-3-6-kg-mockup.png"],
    desc: "Presunto cozido de alta qualidade, sabor suave e textura macia, ideal para fatiamento."
  },
  {
    cod: "20618",
    nome: "LANCHE",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "EMBUTIDOS",
    tipo: "RESFRIADO",
    complemento: "2,5 kg — 4 un",
    peso: "10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/nr9dV3s4/20618-V02-Sabbor-Lanche-188X460-(26521)-mockup.png"],
    desc: "Produto prático para lanches, com sabor agradável e versatilidade no consumo diário."
  },
  {
    cod: "20936",
    nome: "LOMBO TIPO CANADENSE",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "EMBUTIDOS",
    tipo: "DEFUMADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/c1KZ8Zwh/20936-V01-Mister-Pig-Lombo-Tipo-Canadense.png"],
    desc: "Lombo suíno tipo canadense, defumado e com sabor suave, ideal para lanches e refeições."
  },
  {
    cod: "20677",
    nome: "MINI MORTADELA TIPO BOLOGNA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "EMBUTIDOS",
    tipo: "DEFUMADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/c6qFvfYD/20638-V01-Mister-Pig-Mortadela-Tipo-Bologna-GRANDE.png"],
    desc: "Tradição em formato prático. Sabor marcante e textura delicada, perfeita para tábuas de frios e lanches gourmet."
  },
  {
    cod: "20510",
    nome: "LINGUIÇA DE FRANGO FINA APIMENTADA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "800g — 18 un",
    peso: "14,4 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/9Mn8j6fM/20510-V00-Mister-Pig-Linguica-de-Frango-Fina-Apimentada-800-g-Congelada-mockup.png"],
    desc: "Linguiça fina de frango com toque picante, perfeita para grelhar ou fritar, com textura leve e sabor intenso."
  },
  {
    cod: "20511",
    nome: "LINGUIÇA TIPO PAIO 1 KG",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "LINGUIÇAS",
    tipo: "DEFUMADOS",
    complemento: "1 Kg — 12 un",
    peso: "12 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATE +22°C",
    promo: false,
    imgs: ["https://i.postimg.cc/rmPnLBpp/20511-V01-SABBOR-Linguica-Paio-1-kg.png"],
    desc: "Linguiça tipo paio, sabor defumado tradicional, ideal para feijoadas e pratos típicos."
  },
  {
    cod: "20512",
    nome: "LINGUIÇA TIPO PAIO 3 GOMOS",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "LINGUIÇAS",
    tipo: "DEFUMADOS",
    complemento: "PESO VARIÁVEL",
    peso: "10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATE +25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/mD5XGvrk/20512-V00-SABBOR-Linguica-Paio-3-gomos-mockup.png"],
    desc: "Linguiça tipo paio com sabor marcante e defumação especial, perfeita para receitas tradicionais."
  },
  {
    cod: "20603",
    nome: "LINGUIÇA APERITIVO APIMEN. DE FRANGO RESF.",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "LINGUIÇAS",
    tipo: "RESFRIADO",
    complemento: "2,5 kg — 8 un",
    peso: "10 kg",
    conserva: "MANTENHA RESFRIADA DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/7hJBPKCP/20603-V01-SABBOR-Linguica-de-Frango-Fina-Apimentada-Resfriada-2-5-kg-mockup.png"],
    desc: "Linguiça de frango apimentada, pronta para consumo rápido, com sabor equilibrado. Produto resfriado."
  },
  {
    cod: "20604",
    nome: "LINGUIÇA TIPO CALABRESA SABBOR 2,5 KG",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "LINGUIÇAS",
    tipo: "DEFUMADOS",
    complemento: "2,5 kg — 6 un",
    peso: "15 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ +22°C",
    promo: false,
    imgs: ["https://i.postimg.cc/nr9dV3sc/20604-SABBOR-Linguica-Tipo-Calabresa-2-5-kg-mockup.png"],
    desc: "Linguiça calabresa de alta qualidade, ideal para diversos preparos, com sabor defumado característico."
  },
  {
    cod: "20606",
    nome: "LINGUIÇA TIPO CALABRESA 2 GOMOS",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "DEFUMADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ +22°C",
    promo: false,
    imgs: ["https://i.postimg.cc/brS6YmGw/20606-V00-Mister-Pig-Linguica-Tipo-Calabresa-2-Gomos.png"],
    desc: "Linguiça calabresa tradicional, versátil e saborosa, indicada para churrascos e receitas variadas."
  },
  {
    cod: "20905",
    nome: "LINGUIÇA CHURRASCO CONGELADA 800G",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "800g — 18 un",
    peso: "14,4 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/DfWFbFLy/20905-V01-Mister-Pig-Linguica-Churrasco-800-g-Congelada-mockup.png"],
    desc: "Linguiça ideal para churrasco, sabor suculento e preparo prático. Produto congelado."
  },
  {
    cod: "20907",
    nome: "LINGUIÇA TIPO CALABRESA MISTER PIG",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "DEFUMADOS",
    complemento: "2,5 kg — 6 un",
    peso: "15 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ +22°C",
    promo: false,
    imgs: ["https://i.postimg.cc/FFfmJm3z/20907-V02-Mister-Pig-Linguica-Tipo-Calabresa-2-5-kg.png"],
    desc: "Linguiça calabresa com padrão premium, sabor defumado intenso e excelente rendimento."
  },
  {
    cod: "20943",
    nome: "LINGUIÇA SUÍNA APIMENTADA RESF. PCT 4 Kg",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "RESFRIADO",
    complemento: "4kg — 4 un",
    peso: "16 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/y6wKm5yX/20943-V01-Mister-Pig-Linguica-Suina-Apimentada-4-kg-Resfriada.png"],
    desc: "Linguiça suína apimentada em embalagem econômica, ideal para alto consumo. Produto resfriado."
  },
  {
    cod: "20944",
    nome: "LINGUIÇA SUÍNA APIMENTADA CONG. PCT 4 Kg",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "4 kg — 4 un",
    peso: "16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/wxSzXPQV/20944-V01-Mister-Pig-Linguica-Suina-Apimentada-4-kg.png"],
    desc: "Linguiça suína apimentada congelada, com maior durabilidade e excelente rendimento."
  },
  {
    cod: "20901",
    nome: "LINGUIÇA SUÍNA FINA APIMENTADA 800G",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "800 g — 18 un",
    peso: "14,4 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/MXk9n1Rg/20901-V01-Mister-Pig-Linguica-Suina-Fina-Apimentada-800-g-Congelada-mockup.png"],
    desc: "Linguiça suína fina com toque picante, ideal para churrascos e grelhados."
  },
  {
    cod: "20903",
    nome: "LINGUIÇA SUÍNA APIMENTADA CONGELADA 800G",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "800 g — 18 un",
    peso: "14,4 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/PNGSC1Yk/20903-V01-Mister-Pig-Linguica-Suina-Apimentada-800-g-Congelada-mockup.png"],
    desc: "Linguiça suína apimentada, congelada para maior conservação, com sabor marcante."
  },
  {
    cod: "20947",
    nome: "LINGUIÇA SUÍNA CHURRASCO",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "RESFRIADO",
    complemento: "4 kg — 3 un",
    peso: "12 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/66DKrSfz/20947-V01-Mister-Pig-Linguica-Churrasco-4-kg-Resfriada.png"],
    desc: "Linguiça suína ideal para churrasco, com sabor marcante e ótima suculência."
  },
  {
    cod: "20948",
    nome: "LINGUIÇA CHURRASCO SUÍNA CONG.",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "4 kg — 4 un",
    peso: "16 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/Vs3wqTWh/20948-V01-Mister-Pig-Linguica-Churrasco-4-kg-Congelada.png"],
    desc: "Linguiça suína para churrasco, congelada para melhor conservação e praticidade."
  },
  {
    cod: "20949",
    nome: "LINGUIÇA SUÍNA FINA APIMENTADA 3KG",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "3 kg — 3 un",
    peso: "9 kg",
    conserva: "MANTENHA CONGELADA A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/CMW0Gt4T/20949-V00-Mister-Pig-Linguica-Suina-Fina-Apimentada-3-kg.png"],
    desc: "Linguiça suína fina e apimentada em embalagem econômica, ideal para grande consumo."
  },
  {
    cod: "20503",
    nome: "LINGUIÇA APERITIVO APIMEN. DE FRANGO CONG.",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "LINGUIÇAS",
    tipo: "CONGELADO",
    complemento: "2,5 kg — 4 un",
    peso: "10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/63mjNkQp/20503-V01-SABBOR-Linguica-de-Frango-Fina-Apimentada-Congelada-2-5-kg.png"],
    desc: "Linguiça de frango levemente apimentada, prática e saborosa, ideal para petiscos e aperitivos. Produto congelado."
  },
  {
    cod: "20902",
    nome: "LINGUIÇA SUÍNA FINA APIMENTADA RESF. 4KG",
    empresa: "Dom Porquito",
    marca: "SABBOR",
    grupo: "LINGUIÇAS",
    tipo: "RESFRIADO",
    complemento: "4 kg — 4 un",
    peso: "16 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/d16v9PMR/SABBOR-logo-para-outros-fundos.png"],
    desc: "Equilíbrio perfeito entre a suculência da carne suína selecionada e um toque de pimenta na medida certa. Formato fino, ideal para grelhas, chapas ou como aperitivo diferenciado em churrascos."
  },
  {
    cod: "20768",
    nome: "INGREDIENTES PARA FEIJOADA ESPECIAL",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA RESFRIADO DE 0°C A 7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/t70BsFPc/20768-Mister-Pig-Ingredientes-para-Feijoada-1-kg.png"],
    desc: "Mix de carnes selecionadas para feijoada, garantindo praticidade e sabor tradicional."
  },
  {
    cod: "20760",
    nome: "Ponta de Costela Salgada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/rFySvL2r/20760.png"],
    desc: "Produto salgado ideal para pratos tradicionais."
  },
  {
    cod: "20753",
    nome: "Joelho Suíno Salgado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/28j4PfN5/20753.png"],
    desc: "Produto típico para receitas regionais."
  },
  {
    cod: "20755",
    nome: "Língua Suína Salgada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/sDfptRCx/20755.png"],
    desc: "Produto salgado para preparo tradicional."
  },
  {
    cod: "20756",
    nome: "Rabo Suíno Salgado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/5N9wZMW2/20756.png"],
    desc: "Ideal para feijoadas e pratos típicos."
  },
  {
    cod: "20757",
    nome: "Pé Suíno Salgado",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/656dDNx3/20757.png"],
    desc: "Produto tradicional para caldos."
  },
  {
    cod: "20758",
    nome: "Costela Suína Salgada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/Gh3kZ1ns/20758.png"],
    desc: "Corte salgado pronto para preparo."
  },
  {
    cod: "20759",
    nome: "Máscara Suína Salgada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/yY6FwzCR/20759.png"],
    desc: "Produto típico regional."
  },
  {
    cod: "20900",
    nome: "Pele Suína Salgada",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "SALGADOS",
    tipo: "SALGADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/9FXGvjHw/20900.png"],
    desc: "Ideal para preparo de torresmo."
  },
  {
    cod: "20933",
    nome: "BACON EM PEDAÇOS",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "DEFUMADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 5 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/J7ymBmZq/20933-V01-Mister-Pig-Bacon-Pedacos.png"],
    desc: "Bacon em cubos prontos para uso, ideal para incrementar pratos com sabor defumado."
  },
  {
    cod: "20931",
    nome: "BACON EM MANTA MISTER PIG",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "DEFUMADOS",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 15 kg",
    conserva: "MANTENHA EM LOCAL SECO E FRESCO ATÉ 25°C",
    promo: false,
    imgs: ["https://i.postimg.cc/v81M6Mfv/20931-V01-Mister-Pig-Bacon-Manta.png"],
    desc: "Bacon em manta de alta qualidade, ideal para cortes personalizados e diversas receitas."
  },
  {
    cod: "20942",
    nome: "BISTECA SUÍNA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PESO VARIÁVEL",
    peso: "Aprox. 10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/59ZJBGS5/20942-V00-Mister-Pig-Bisteca-Suina-Congelada-mockup.png"],
    desc: "Corte tradicional suíno, versátil e saboroso, ideal para fritar ou grelhar."
  },
  {
    cod: "481",
    nome: "BATATA CRISPY COATED PREMIUM 10mm 12kg",
    empresa: "Fripal",
    marca: "FARM FRITE",
    grupo: "BATATA",
    tipo: "CONGELADO",
    complemento: "2 kg — 6 un",
    peso: "12 kg",
    conserva: "MANTENHA CONGELADO A -18°C",
    promo: false,
    imgs: ["https://i.postimg.cc/bYRJDrpy/481.png"],
    desc: "Batatas palito de corte super fino (7mm), garantindo uma crocância excepcional e fritura rápida. Ideais para quem busca elegância no prato e alto rendimento."
  },
  {
    cod: "488",
    nome: "BATATA FARM FRITES FRIES 7mm 12.5kg",
    empresa: "Fripal",
    marca: "FARM FRITE",
    grupo: "BATATA",
    tipo: "CONGELADO",
    complemento: "2,5 kg — 5 un",
    peso: "12,5 kg",
    conserva: "MANTENHA CONGELADO A -18°C",
    promo: false,
    imgs: ["https://i.postimg.cc/DfcZJ0nb/488.png"],
    desc: "A clássica batata palito de 10mm, com o equilíbrio perfeito entre o interior macio e a casca dourada. Versátil, é a escolha ideal para acompanhar porções e pratos principais."
  },
  {
    cod: "60108",
    nome: "BATATA FARM FRITES TRAD 10MM 12kg",
    empresa: "Fripal",
    marca: "FARM FRITE",
    grupo: "BATATA",
    tipo: "CONGELADO",
    complemento: "2 kg — 6 un",
    peso: "12 kg",
    conserva: "MANTENHA CONGELADO A -18°C",
    promo: false,
    imgs: ["https://i.postimg.cc/1RKtnXs4/60108.png"],
    desc: "Batatas pré-fritas de 10mm que oferecem o melhor custo-benefício para o seu negócio. Mantêm a consistência e o sabor após a fritura, sendo perfeitas para delivery e lanchonetes."
  },
  {
    cod: "60109",
    nome: "BATATA STAR FRITES 10 MM 10kg",
    empresa: "Fripal",
    marca: "FARM FRITE",
    grupo: "BATATA",
    tipo: "CONGELADO",
    complemento: "2 kg — 5 un",
    peso: "10 kg",
    conserva: "MANTENHA CONGELADO A -18°C",
    promo: false,
    imgs: ["https://i.postimg.cc/1RKtnXsX/60109.png"],
    desc: "A qualidade Star Frites em embalagem prática de 2kg. Batatas palito de 10mm, ideais para operações menores ou controle rígido de estoque, garantindo sempre um produto fresquinho."
  },
  {
    cod: "624",
    nome: "BACON FATIADO CONGELADO",
    empresa: "Fripal",
    marca: "MISTER PIG",
    grupo: "FATIADO",
    tipo: "CONGELADO",
    complemento: "Aprox. 900g",
    peso: "?",
    conserva: "MANTER CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/wjGXf5bT/Mockup-Bacon-Fatiado-fundo-624.png"],
    desc: "O sabor defumado com máxima praticidade. Fatias padronizadas que garantem uniformidade no preparo e crocância irresistível. Ideal para hambúrgueres, porções e pratos gourmet."
  },
  {
    cod: "274",
    nome: "LANCHE SABBOR FATIADO",
    empresa: "Fripal",
    marca: "SABBOR",
    grupo: "FATIADO",
    tipo: "RESFRIADO",
    complemento: "Aprox. 150g",
    peso: "4,5 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/ht5Ly83t/Mockup-Lanche-Fatiado-fundo-transparente274.png"],
    desc: "Desenvolvido para o food service. Fatias que se soltam facilmente, sabor equilibrado e excelente custo-benefício para sanduíches quentes ou frios."
  },
  {
    cod: "277",
    nome: "LINGUIÇA TIPO CALABRESA SABBOR FATIADO",
    empresa: "Fripal",
    marca: "SABBOR",
    grupo: "FATIADO",
    tipo: "RESFRIADO",
    complemento: "Aprox. 500g",
    peso: "4,5 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/2SKQcdX6/Mockup-Lingiuca-Calabresa-Fatiada-fundo-transparente-277.png"],
    desc: "A clássica calabresa Sabbor pronta para uso. Fatias com espessura ideal para coberturas de pizzas, recheios de salgados e finalização de massas."
  },
  {
    cod: "443",
    nome: "LOMBO TIPO CANADENSE DEFUMADO FATIADO",
    empresa: "Fripal",
    marca: "MISTER PIG",
    grupo: "FATIADO",
    tipo: "RESFRIADO",
    complemento: "Aprox. 150g",
    peso: "4,5 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/y8bmQhrx/Mockup-Lombo-Canadense-fundo-transparente443.png"],
    desc: "Nobreza e leveza em cada fatia. Defumação cuidadosa, sabor sofisticado e baixo teor de gordura. Perfeito para tábuas de frios premium e lanches naturais."
  },
  {
    cod: "276",
    nome: "MORTADELA BOLOGNA MISTER PIG FATIADO",
    empresa: "Fripal",
    marca: "MISTER PIG",
    grupo: "FATIADO",
    tipo: "RESFRIADO",
    complemento: "Aprox. 150g",
    peso: "4,5 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/K8HPq7sL/Mockup-Mortadela-fatiado-fundo-transparente276.png"],
    desc: "Inspirada na tradição italiana, textura macia e bouquet de especiarias único. Fatiada finamente para realçar o sabor em lanches e petiscos."
  },
  {
    cod: "604",
    nome: "QUEIJO MUSSARELA LAT VIDA FATIADO",
    empresa: "Fripal",
    marca: "LAT VIDA",
    grupo: "FATIADO",
    tipo: "RESFRIADO",
    complemento: "Aprox. 150g",
    peso: "4,5 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/3xcXSjbv/Mockup-Mussarela-fundo-transparente604.png"],
    desc: "Mussarela selecionada com excelente derretimento e elasticidade. Fatias padronizadas para montagem de pratos, garantindo aquele visual dourado e apetitoso."
  },
  {
    cod: "272",
    nome: "PRESUNTO COZIDO SABBOR FATIADO",
    empresa: "Fripal",
    marca: "SABBOR",
    grupo: "FATIADO",
    tipo: "RESFRIADO",
    complemento: "Aprox. 150g",
    peso: "4,5 kg",
    conserva: "MANTER RESFRIADO 0°C A +7°C",
    promo: false,
    imgs: ["https://i.postimg.cc/wjGXf5bN/Mockup-Presunto-fundo-transparente-272.png"],
    desc: "O clássico indispensável com a garantia Sabbor. Produzido com pernil selecionado, fatias rosadas e suculentas. Ideal para buffets, padarias e montagem de pizzas."
  },
  {
    cod: "460",
    nome: "MANTEIGA SABBOR 500G",
    empresa: "Fripal",
    marca: "SABBOR",
    grupo: "MANTEIGA",
    tipo: "RESFRIADO",
    complemento: "500g — 12 un",
    peso: "6 kg",
    conserva: "MANTENHA REFRIGERADO DE 1°C A 10°C",
    promo: false,
    imgs: ["https://i.postimg.cc/v8vBgTbQ/460-MANTEIGA-SABBOR-500G.png"],
    desc: "Manteiga de qualidade superior com sabor autêntico e textura cremosa. A embalagem de 500g é ideal para famílias e transformadores que buscam rendimento e praticidade na cozinha, seja para passar no pão ou para receitas culinárias."
  },
  {
    cod: "461",
    nome: "MANTEIGA SABBOR 200G",
    empresa: "Fripal",
    marca: "SABBOR",
    grupo: "MANTEIGA",
    tipo: "RESFRIADO",
    complemento: "200g — 24 un",
    peso: "4,8 kg",
    conserva: "MANTENHA REFRIGERADO DE 1°C A 10°C",
    promo: false,
    imgs: ["https://i.postimg.cc/RCTF6h4v/461-MANTEIGA-SABBOR-200G.png"],
    desc: "A clássica Manteiga Sabbor em embalagem compacta e prática. Perfeita para o consumo diário, garante frescor e cremosidade em cada uso. Possui o equilíbrio ideal de sal para realçar o sabor dos seus cafés da manhã e lanches."
  },
  {
    cod: "263",
    nome: "QUEIJO MUSSARELA PROCESSADO EM BARRA",
    empresa: "Fripal",
    marca: "PURANATA",
    grupo: "QUEIJO",
    tipo: "RESFRIADO",
    complemento: "4 kg — 4 un",
    peso: "16 kg",
    conserva: "MANTENHA RESFRIADO 1ºC A 10ºC",
    promo: false,
    imgs: ["https://i.postimg.cc/BbCc7GLC/263.png"],
    desc: "Opção versátil e de alto rendimento, este Queijo Mussarela Processado é a solução inteligente para o dia a dia na cozinha. Apresenta uma textura macia, ótimo custo-benefício e desempenho consistente sob aquecimento, sendo indispensável para montagem de sanduíches, salgados e gratinados rápidos."
  },
  {
    cod: "603",
    nome: "QUEIJO MUSSARELA PROCESSADO LAT VIDA",
    empresa: "Fripal",
    marca: "LAT VIDA",
    grupo: "QUEIJO",
    tipo: "RESFRIADO",
    complemento: "3 kg — 6 un",
    peso: "18 kg",
    conserva: "MANTENHA RESFRIADO  1°C A 7ºC",
    promo: false,
    imgs: ["https://i.postimg.cc/GtjJg18x/603-quijo-musarela-latvida.png"],
    desc: "O Queijo Mussarela Processado Lat Vida oferece o equilíbrio perfeito entre sabor suave e funcionalidade. Desenvolvido para garantir uma derretibilidade uniforme e excelente fatiamento, é ideal para o uso profissional em lanches, pizzas e preparos culinários que exigem padronização e um toque lácteo de qualidade."
  },
  {
    cod: "20749",
    nome: "MEIA CARCACA",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PV (CX C/ 70 KG)",
    peso: "70 kg",
    conserva: "MANTENHA CONGELADO A -12C",
    promo: false,
    imgs: ["https://i.postimg.cc/mkwvTqLx/20749-10.png", "https://i.postimg.cc/Y035tVpJ/20749-11.png", "https://i.postimg.cc/brT7qMz3/20749-2.png", "https://i.postimg.cc/KjN6mVZQ/20749-3.png", "https://i.postimg.cc/QCb2jPX4/20749-5.png","https://i.postimg.cc/ZncGJgTs/20749-6.png"	,"https://i.postimg.cc/J0qfRg1d/20749-7.png"	,"https://i.postimg.cc/yxPM75VL/20749-8.png"	,"https://i.postimg.cc/fyKGMFwF/20749-9.png"
],
    desc: "Produto de alta versatilidade, ideal para açougues, frigoríficos e indústrias de processamento. Oferece excelente rendimento, carne fresca e padrão de qualidade rigoroso para cortes personalizados."
  },
  {
    cod: "20750",
    nome: "LOMBO SUINO CONGELADO",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PV (CX C/ 10 KG)",
    peso: "10 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/kGc07ZnL/20750-1.png", "https://i.postimg.cc/sxck38jz/20750-2.png", "https://i.postimg.cc/yxPM751s/20750-3.png", "https://i.postimg.cc/L5Tcm79F/20750-4.png", "https://i.postimg.cc/KjN6mVGy/20750-5.png"],
    desc: "Corte nobre e macio, com baixo teor de gordura. Congelado individualmente para preservar o sabor, a suculência e os nutrientes. Perfeito para pratos elaborados, assados ou grelhados de alta gastronomia."
  },
  {
    cod: "20728",
    nome: "PERNIL SUINO SEM OSSO",
    empresa: "Dom Porquito",
    marca: "MISTER PIG",
    grupo: "CORTE",
    tipo: "CONGELADO",
    complemento: "PV (CX C/ 18 KG)",
    peso: "18 kg",
    conserva: "MANTENHA CONGELADO A -12°C",
    promo: false,
    imgs: ["https://i.postimg.cc/B6xWVbRD/20728-1.png", "https://i.postimg.cc/gJv9Tj18/20728-2.png", "https://i.postimg.cc/zBnmcv4n/20728-3.png", "https://i.postimg.cc/0jPgRxqz/20728-4.png"],
    desc: "Praticidade e economia para o seu negócio. Carne selecionada, limpa e pronta para o preparo. Ideal para assados, recheados ou para a produção de embutidos e pratos de grande escala, garantindo o melhor aproveitamento da peça."
  }
];
